version: '3.8'

services:
  pandore:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pandore
    environment:
      - PANDORE_PORT=8000
      - TERM=xterm-256color
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    volumes:
      - ./downloads:/app/downloads
      - ./pandore_frontend:/app/pandore_frontend
    restart: always