# Format : URL,Animateur: NomAffiché-ID
# Exemple : https://www.tiktok.com/@utilisateur/live,Animateur: Nom_Affiché-identifiant
https://www.tiktok.com/@boboziofficiel1/live,Animateur: Bobozi
https://www.tiktok.com/@raoul.le.blanc274/live,Animateur: Raoul
